### ISSUE TITLE
CopyFile potentially breaks permissions

### ISSUE THREAD

**Issue by mudler** [mudler/luet#10]
https://github.com/mudler/luet/blob/802adac5ee90e65808fe3aed2dcb175c247d8b51/pkg/compiler/artifact.go#L67

It is not a real issue as the file is copied back and permissions restored,  but we should just copy files and ensure folders have the same permissions

**Comment by geaaru** [comment]
Note: we need to remember to handle files with extra attributes/capabilities:
```
getcap /bin/ping
/bin/ping = cap_net_raw+ep
```

**Comment by mudler** [comment]
We don't handle this directly anymore, but we should dig if this is a problem or not. And open new issues as required

**Comment by mudler** [comment]
It doesn't seem to be an issue anymore, feel free to reopen if this is still an issue
