### ISSUE TITLE
Feature: luet repo search

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#118]
Related to issue #46 we need to supply a way for retrieve the list of repositories and sync mirrors lists.

Hereinafter, a list of possible changes:

1) Add field `community` to LuetRepository struct to divide repositories available from community from repositories that are only private with a static URL list definition

2) Add `luet repo search` command for retrieve list of the repositories

Example:
```
$# luet repo search
luet-entropy-repo    Luet Entropy Repository
luet-embedded       Luet Embedded Repository
...
```
This command read list of the repositories from list of URLs defined on `community_repos_urls`:
```yaml
community_repos_urls:
   - https://<myhost>/<path>/community_repos1.yaml
   - https://<myhost>/<path>/community_repos2.yaml
```

3) Add `luet repo install <name>` command that add repository file under /etc/luet/repos.conf.d

4) Add `luet repo sync <name>` command that permit to sync repositories mirrors list and data

**Comment by mudler** [comment]
I would instead split from `official` and not officials ones, instead of having all the community labeled as `community`. In this way we can always promote new repositories whenever they are `trusted`, or `official` for example.

**Comment by geaaru** [comment]
The `community` field is used to identify what repositories are installed and fetched remotely from repositories that are manually configured. Only on `community` repositories will be possible to execute `luet repo sync <repo>`.
I agree with the `official` repos trusted but we need a way to identify if it's a repository fetched through the remote list (command `repo install`) or not.
Have you some ideas for a different name?

**Comment by geaaru** [comment]
The idea is to use an external extension for `luet` for handle remote index file with the list of the repository. In this way, luet core API will be easier.

**Comment by mudler** [comment]
as of today this lost relevance as we have `luet repo add` and the concept of index repositories to collect repositories definition. Closing this
