### ISSUE TITLE
Spinner appears after prompt before user has made selection

### ISSUE THREAD

**Issue by optiz0r** [mudler/luet#153]
Example: `luet uninstall foo`

luet will by default display what would be done, and show a yes/no prompt before proceeding. At the moment the spinner appears immediately on the next line after the prompt and begins animating.

This is confusing, because it looks like luet has already started the operation, when actually it's waiting for input. Due to the animation constantly redrawing the line, if the user has entered anything, it's promptly hidden from view. It's also scary, because it looks like the operation has begun without confirmation. 

Spinner should only be started after the user has entered their selection.

**Comment by mudler** [comment]
That should be already fixed in develop 👍 https://github.com/mudler/luet/commit/18d9366bca3732d034ee234fd237c16ee6568557

**Comment by mudler** [comment]
That should be fixed in the new release! L
Please reopen if necessary 👍
