### ISSUE TITLE
luet install --output json seems to print non-json output to stdout

### ISSUE THREAD

**Issue by optiz0r** [mudler/luet#155]
The first time luet tries to install a package after enabling a repository, it has to download the repository definitions. It seems to print status output to stdout even when json output is requested. The output thus breaks json parsing.

```
Error: /Stage[main]/Sihnon::Luet_test/Package[sys-process/htop]: Could not evaluate: 765: unexpected token at ' tree.tar.gz -    0% [               {"packages":[{"category":"sys-process","hidden":false,"name":"htop","repository":"mocaccino-portage-stable","target":"","version":"2.2.0+2"}]}
'
```

The status outout should either be sent to stderr, or completely suppressed when using an output format other than `terminal`

**Comment by mudler** [comment]
That seems odd as we use it to catch the output everywhere. Do you have debug enables in your config?

**Comment by optiz0r** [comment]
The error was being picked up by puppet after just running the luet install script, installing the repository, and then installed the package, it would fail on the third step. I can't reproduce this now, so I'll close and re-open if I see it.
