### ISSUE TITLE
Extension to move package images across registries

### ISSUE THREAD

**Issue by mudler** [mudler/luet#161]
See also: https://github.com/mocaccinoOS/issue-tracker/issues/40

At the moment the procedure is manual - but it can be simplified a lot if we just ship an extension for it, the manual steps that already allows this to be done would be:

```bash
$ luet tree images [opts] <package> # Grab the images hashes
$ docker pull && docker tag  # for each package image in a registry
$ docker push # for each image, with the new tag containing the new registry location
```

**Comment by welele08** [comment]
Thank for help.
It seem that `luet tree images <package>` only list images "with build step" and hide images "with prelude step".
There is no image tagged "builder-*" in the list.

**Comment by mudler** [comment]
yes, you typically don't really need those if you are deriving packages from others.  We need to deliver #158 first to address that specific point, but it's low prio unless blocks you from building derivative packages ( would be nice to have a confirmation 🙂 )

**Comment by welele08** [comment]
I also think I don't need "builder-" images. I need to adjust my building process (maybe use --nodeps more aggressively. :p )

**Comment by mudler** [comment]
> I also think I don't need "builder-" images. I need to adjust my building process (maybe use --nodeps more aggressively. :p )

You can use `--only-target-package` , in this way won't skip building deps by default, but only if images are already there 🙂 https://luet-lab.github.io/docs/docs/concepts/overview/build_packages/#build-faster

**Comment by welele08** [comment]
--only-target-package doesn't prevent from building dep from `portage-tree` repo in my case. 

I have a `build.yaml` as follow
`unpack: true
includes:
- /bin$|/bin/.*
- /dev$|/dev/.*
- /etc$
# TODO: Add /etc to config protect
- /etc$|/etc/.*
- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
prelude:
- cp -rvf package.use/* /etc/portage/package.use/
- cp -rvf package.accept_keywords/* /etc/portage/package.accept_keywords/
- emerge  app-eselect/eselect-repository app-portage/layman
- layman -L
- echo y|layman -a sabayon
- echo y|layman -a sabayon-distro
- echo 'PYTHON_SINGLE_TARGET="python3_7"' >>/etc/portage/make.conf
steps:
- ACCEPT_LICENSE=* emerge @xfce

- for file in $(find /usr/share/icons -name "icon-theme.cache"); do rm $file; done
requires:
- category: "layers"
  name: "X"
  version: ">0.1"`

and the same makefile as in `portage-tree` repo, with `--only-target-package  --skip-if-metadata-exists=true --push --pull` and a customized `REPO_CACHE`. (portage-cache is a git submodule and I add `-t` on it ) 

A `PACKAGES="distro/gnome" make rebuild`  launch the building launch the build for `layer/gentoo-stage3`, `layer/gentoo-portage`, `development/mocaccino-overlay-core` and all dep for `layers/X` , including the `builder-*` images.

**Comment by mudler** [comment]
> --only-target-package doesn't prevent from building dep from `portage-tree` repo in my case.
> 
> I have a `build.yaml` as follow
> `unpack: true
> includes:
> 
> * /bin$|/bin/.*
> * /dev$|/dev/.*
> * /etc$
> 
> # TODO: Add /etc to config protect
> * /etc$|/etc/.*
> * /home$|/home/.*
> * /lib$|/lib.*
> * /media$|/media/.*
> * /mnt$|/mnt/.*
> * /opt$|/opt/.*
> * /root$|/root/.*
> * /run$|/run/.*
> * /sbin$|/sbin/.*
> * /usr$|/usr/.*
> * /var$|/var/.*
>   prelude:
> * cp -rvf package.use/* /etc/portage/package.use/
> * cp -rvf package.accept_keywords/* /etc/portage/package.accept_keywords/
> * emerge  app-eselect/eselect-repository app-portage/layman
> * layman -L
> * echo y|layman -a sabayon
> * echo y|layman -a sabayon-distro
> * echo 'PYTHON_SINGLE_TARGET="python3_7"' >>/etc/portage/make.conf
>   steps:
> * ACCEPT_LICENSE=* emerge @xfce
> * for file in $(find /usr/share/icons -name "icon-theme.cache"); do rm $file; done
>   requires:
> * category: "layers"
>   name: "X"
>   version: ">0.1"`
> 
> and the same makefile as in `portage-tree` repo, with `--only-target-package --skip-if-metadata-exists=true --push --pull` and a customized `REPO_CACHE`. (portage-cache is a git submodule and I add `-t` on it )
> 
> A `PACKAGES="distro/gnome" make rebuild` launch the building launch the build for `layer/gentoo-stage3`, `layer/gentoo-portage`, `development/mocaccino-overlay-core` and all dep for `layers/X` , including the `builder-*` images.

I think that's a portage-tree issue rather than a luet one, atm we are rebuilding several layers there, but that being said, I need to ask you:

- luet version currently used
- what's the commit on portage-tree your submodule is pointing too
- full log of `--only-taget-package` and `--nodeps`. Are they showing the same behavior?

Besides, can you try to pull the docker images from the repo manually? The one that `luet tree images` reports?

**Comment by welele08** [comment]
I docker pull from quay, tagged and docker pull to my personal docker registry
- luet version : 0.9.16
- portage-tree commit : 729a0fcad787db10c43f9b123c5af71a22d037e7

**With --nodeps**
` Loading tree portage-tree
 Loading tree packages
 Building in /home/welele/mocaccino/capesos-from-gentoo/build
⠈  📦  Compiling distro/concours-base-20201226 .... ☕
 🚀  All dependencies are satisfied, building package requested by the user distro/concours-base-20201226
 📦  distro/concours-base-20201226  Using image:  xxx/capesos-from-gentoo/luet:c77b4e6a5eaf458040ccd1c75c03544a43b6c37077e66c352e1fbe4360f86126
 📦  distro/concours-base-20201226 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:c77b4e6a5eaf458040ccd1c75c03544a43b6c37077e66c352e1fbe4360f86126 as xxx/capesos-from-gentoo/luet:builder-3601c9c2e610035442225ab2526d3d91 with prelude steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:builder-3601c9c2e610035442225ab2526d3d91
 📦  distro/concours-base-20201226 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-3601c9c2e610035442225ab2526d3d91 as xxx/capesos-from-gentoo/luet:3c43d4317f705b63797d8a6a2a7e1b7ef8e9a448b5bcadc8791e344bfc7bc7f7 with build steps
🚧   Failed to download 'xxx/capesos-from-gentoo/luet:3c43d4317f705b63797d8a6a2a7e1b7ef8e9a448b5bcadc8791e344bfc7bc7f7'. Will keep going and build the image unless you use --fatal
🚧   Failed pulling image: Error response from daemon: manifest for registry.gitlab.welele.ml/avril.francois/capesos-from-gentoo/luet:3c43d4317f705b63797d8a6a2a7e1b7ef8e9a448b5bcadc8791e344bfc7bc7f7 not found: manifest unknown: manifest unknown
: exit status 1`

Then, it fail during cause of use mask adjustment (emerge/package problem=normal, my job ;) )
`Step 7/8 : RUN ACCEPT_LICENSE=* emerge @xfce
 ---> Running in 43313ccd9def`


**without --nodeps and --only-target-packages**
` Loading tree portage-tree
 Loading tree packages
 Building in /home/welele/mocaccino/capesos-from-gentoo/build
⠈  📦  Compiling distro/concours-base-20201226 .... ☕ 
 🌳  Build dependencies for distro/concours-base-20201226
  ↪  layer/gentoo-stage3-0.20201125 🍃 
  ↪  layer/gentoo-portage-0.20201111+2 🍃 
  ↪  development/mocaccino-overlay-core-0.20210101+1 🍃 
  ↪  layers/system-core-0.20210101+2 🍃 
  ↪  layers/clang-10-10.0.1+6 🍃 
  ↪  development/mocaccino-overlay-x-0.20210104 🍃 
  ↪  layers/system-x-0.20210104+1 🍃 
  ↪  layers/sys-fs-0.4+2 🍃 
  ↪  layers/X-0.3+13 🍃 
 📦  1/9 distro/concours-base-20201226 ⤑ 🔨  build layer/gentoo-stage3-0.20201125  starts
 📦  layer/gentoo-stage3-0.20201125 🐋  Generating 'builder' image from alpine as xxx/capesos-from-gentoo/luet:dc830e46b768dd530f05dd3ea461f82beca7c8497a60dd5923227d60cfd71ef9 with prelude steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:dc830e46b768dd530f05dd3ea461f82beca7c8497a60dd5923227d60cfd71ef9
 📦  layer/gentoo-stage3-0.20201125 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:dc830e46b768dd530f05dd3ea461f82beca7c8497a60dd5923227d60cfd71ef9 as xxx/capesos-from-gentoo/luet:e1eb7be13068a1fb7956b4b68d20e74f9033956b453a2fbc7436e0dab28e50c2 with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:e1eb7be13068a1fb7956b4b68d20e74f9033956b453a2fbc7436e0dab28e50c2
 📦  1/9 distro/concours-base-20201226 ⤑ 🔨  build layer/gentoo-stage3-0.20201125 ✅  Done
 📦  2/9 distro/concours-base-20201226 ⤑ 🔨  build layer/gentoo-portage-0.20201111+2  starts
 📦  layer/gentoo-portage-0.20201111+2 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:e1eb7be13068a1fb7956b4b68d20e74f9033956b453a2fbc7436e0dab28e50c2 as xxx/capesos-from-gentoo/luet:builder-e522072c8b206358eced3c5a82350b40 with prelude steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:builder-e522072c8b206358eced3c5a82350b40
 📦  layer/gentoo-portage-0.20201111+2 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-e522072c8b206358eced3c5a82350b40 as xxx/capesos-from-gentoo/luet:b13a68b3917819f6abbf5c1d10bfdcb86a9ff998f2ae13d30e338c50882a507b with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:b13a68b3917819f6abbf5c1d10bfdcb86a9ff998f2ae13d30e338c50882a507b
 📦  2/9 distro/concours-base-20201226 ⤑ 🔨  build layer/gentoo-portage-0.20201111+2 ✅  Done
 📦  3/9 distro/concours-base-20201226 ⤑ 🔨  build development/mocaccino-overlay-core-0.20210101+1  starts
 📦  development/mocaccino-overlay-core-0.20210101+1 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:b13a68b3917819f6abbf5c1d10bfdcb86a9ff998f2ae13d30e338c50882a507b as xxx/capesos-from-gentoo/luet:4292a46b97d0db2c84acdf47ac656b515200edad284e4380c0988fd69f3f7ca0 with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:4292a46b97d0db2c84acdf47ac656b515200edad284e4380c0988fd69f3f7ca0
 📦  3/9 distro/concours-base-20201226 ⤑ 🔨  build development/mocaccino-overlay-core-0.20210101+1 ✅  Done
 📦  4/9 distro/concours-base-20201226 ⤑ 🔨  build layers/system-core-0.20210101+2  starts
 📦  layers/system-core-0.20210101+2 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:4292a46b97d0db2c84acdf47ac656b515200edad284e4380c0988fd69f3f7ca0 as xxx/capesos-from-gentoo/luet:builder-c77ffb436e99b7889748147765dbc6e9 with prelude steps
[1;33;40m🚧   Failed to download 'xxx/capesos-from-gentoo/luet:builder-c77ffb436e99b7889748147765dbc6e9'. Will keep going and build the image unless you use --fatal[0m
[1;33;40m🚧   Failed pulling image: Error response from daemon: manifest for xxx/capesos-from-gentoo/luet:builder-c77ffb436e99b7889748147765dbc6e9 not found: manifest unknown: manifest unknown
: exit status 1[0m
 🐋  Building image xxx/capesos-from-gentoo/luet:builder-c77ffb436e99b7889748147765dbc6e9 done
 🐋  Pushed image: xxx/capesos-from-gentoo/luet:builder-c77ffb436e99b7889748147765dbc6e9
 📦  layers/system-core-0.20210101+2 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-c77ffb436e99b7889748147765dbc6e9 as xxx/capesos-from-gentoo/luet:f2cb413acf4783ca8049bf01b8be133d9db64b57c5aef4e058bd7c9782cd04b9 with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:f2cb413acf4783ca8049bf01b8be133d9db64b57c5aef4e058bd7c9782cd04b9
 📦  4/9 distro/concours-base-20201226 ⤑ 🔨  build layers/system-core-0.20210101+2 ✅  Done
 📦  5/9 distro/concours-base-20201226 ⤑ 🔨  build layers/clang-10-10.0.1+6  starts
 📦  layers/clang-10-10.0.1+6 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:f2cb413acf4783ca8049bf01b8be133d9db64b57c5aef4e058bd7c9782cd04b9 as xxx/capesos-from-gentoo/luet:builder-2f5798f4f552c79ebceaeaacddb5de1d with prelude steps
[1;33;40m🚧   Failed to download 'xxx/capesos-from-gentoo/luet:builder-2f5798f4f552c79ebceaeaacddb5de1d'. Will keep going and build the image unless you use --fatal[0m
[1;33;40m🚧   Failed pulling image: Error response from daemon: manifest for xxx/capesos-from-gentoo/luet:builder-2f5798f4f552c79ebceaeaacddb5de1d not found: manifest unknown: manifest unknown
: exit status 1[0m
 🐋  Building image xxx/capesos-from-gentoo/luet:builder-2f5798f4f552c79ebceaeaacddb5de1d done
 🐋  Pushed image: xxx/capesos-from-gentoo/luet:builder-2f5798f4f552c79ebceaeaacddb5de1d
 📦  layers/clang-10-10.0.1+6 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-2f5798f4f552c79ebceaeaacddb5de1d as xxx/capesos-from-gentoo/luet:a90a0d1a9e21b00f2e982202750bf767c2dea31f06426b49e30c4e422afff5dd with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:a90a0d1a9e21b00f2e982202750bf767c2dea31f06426b49e30c4e422afff5dd
 📦  5/9 distro/concours-base-20201226 ⤑ 🔨  build layers/clang-10-10.0.1+6 ✅  Done
 📦  6/9 distro/concours-base-20201226 ⤑ 🔨  build development/mocaccino-overlay-x-0.20210104  starts
 📦  development/mocaccino-overlay-x-0.20210104 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:a90a0d1a9e21b00f2e982202750bf767c2dea31f06426b49e30c4e422afff5dd as xxx/capesos-from-gentoo/luet:d7c6c8fa91d7df40e24384fba88210b70e4d4f292770f650a658d1b814aa5b19 with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:d7c6c8fa91d7df40e24384fba88210b70e4d4f292770f650a658d1b814aa5b19
 📦  6/9 distro/concours-base-20201226 ⤑ 🔨  build development/mocaccino-overlay-x-0.20210104 ✅  Done
 📦  7/9 distro/concours-base-20201226 ⤑ 🔨  build layers/system-x-0.20210104+1  starts
 📦  layers/system-x-0.20210104+1 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:d7c6c8fa91d7df40e24384fba88210b70e4d4f292770f650a658d1b814aa5b19 as xxx/capesos-from-gentoo/luet:builder-bedef2727170a4c2db651d50b8a234f3 with prelude steps
[1;33;40m🚧   Failed to download 'xxx/capesos-from-gentoo/luet:builder-bedef2727170a4c2db651d50b8a234f3'. Will keep going and build the image unless you use --fatal[0m
[1;33;40m🚧   Failed pulling image: Error response from daemon: manifest for xxx/capesos-from-gentoo/luet:builder-bedef2727170a4c2db651d50b8a234f3 not found: manifest unknown: manifest unknown
: exit status 1[0m
 🐋  Building image xxx/capesos-from-gentoo/luet:builder-bedef2727170a4c2db651d50b8a234f3 done
 🐋  Pushed image: xxx/capesos-from-gentoo/luet:builder-bedef2727170a4c2db651d50b8a234f3
 📦  layers/system-x-0.20210104+1 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-bedef2727170a4c2db651d50b8a234f3 as xxx/capesos-from-gentoo/luet:8240939db4fb93577117302f5ce77b8d71017eb3d4724c3c7c4831b17672cf5d with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:8240939db4fb93577117302f5ce77b8d71017eb3d4724c3c7c4831b17672cf5d
 📦  7/9 distro/concours-base-20201226 ⤑ 🔨  build layers/system-x-0.20210104+1 ✅  Done
 📦  8/9 distro/concours-base-20201226 ⤑ 🔨  build layers/sys-fs-0.4+2  starts
 📦  layers/sys-fs-0.4+2 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:8240939db4fb93577117302f5ce77b8d71017eb3d4724c3c7c4831b17672cf5d as xxx/capesos-from-gentoo/luet:84a5c37b3e75ca07cd34340eb546fe128b54e541c35107db6c727a8098a96f45 with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:84a5c37b3e75ca07cd34340eb546fe128b54e541c35107db6c727a8098a96f45
 📦  8/9 distro/concours-base-20201226 ⤑ 🔨  build layers/sys-fs-0.4+2 ✅  Done
 📦  9/9 distro/concours-base-20201226 ⤑ 🔨  build layers/X-0.3+13  starts
 📦  layers/X-0.3+13 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:84a5c37b3e75ca07cd34340eb546fe128b54e541c35107db6c727a8098a96f45 as xxx/capesos-from-gentoo/luet:builder-79a4b1db60e38bdcdf4ea988de7227b1 with prelude steps
[1;33;40m🚧   Failed to download 'xxx/capesos-from-gentoo/luet:builder-79a4b1db60e38bdcdf4ea988de7227b1'. Will keep going and build the image unless you use --fatal[0m
[1;33;40m🚧   Failed pulling image: Error response from daemon: manifest for xxx/capesos-from-gentoo/luet:builder-79a4b1db60e38bdcdf4ea988de7227b1 not found: manifest unknown: manifest unknown
: exit status 1[0m
 🐋  Building image xxx/capesos-from-gentoo/luet:builder-79a4b1db60e38bdcdf4ea988de7227b1 done
 🐋  Pushed image: xxx/capesos-from-gentoo/luet:builder-79a4b1db60e38bdcdf4ea988de7227b1
 📦  layers/X-0.3+13 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-79a4b1db60e38bdcdf4ea988de7227b1 as xxx/capesos-from-gentoo/luet:c77b4e6a5eaf458040ccd1c75c03544a43b6c37077e66c352e1fbe4360f86126 with build steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:c77b4e6a5eaf458040ccd1c75c03544a43b6c37077e66c352e1fbe4360f86126
 📦  9/9 distro/concours-base-20201226 ⤑ 🔨  build layers/X-0.3+13 ✅  Done
 🚀  All dependencies are satisfied, building package requested by the user distro/concours-base-20201226
 📦  distro/concours-base-20201226  Using image:  xxx/capesos-from-gentoo/luet:c77b4e6a5eaf458040ccd1c75c03544a43b6c37077e66c352e1fbe4360f86126
 📦  distro/concours-base-20201226 🐋  Generating 'builder' image from xxx/capesos-from-gentoo/luet:c77b4e6a5eaf458040ccd1c75c03544a43b6c37077e66c352e1fbe4360f86126 as xxx/capesos-from-gentoo/luet:builder-3601c9c2e610035442225ab2526d3d91 with prelude steps
 🐋  Downloaded image: xxx/capesos-from-gentoo/luet:builder-3601c9c2e610035442225ab2526d3d91
 📦  distro/concours-base-20201226 🐋  Generating 'package' image from xxx/capesos-from-gentoo/luet:builder-3601c9c2e610035442225ab2526d3d91 as xxx/capesos-from-gentoo/luet:3c43d4317f705b63797d8a6a2a7e1b7ef8e9a448b5bcadc8791e344bfc7bc7f7 with build steps
[1;33;40m🚧   Failed to download 'xxx/capesos-from-gentoo/luet:3c43d4317f705b63797d8a6a2a7e1b7ef8e9a448b5bcadc8791e344bfc7bc7f7'. Will keep going and build the image unless you use --fatal[0m
[1;33;40m🚧   Failed pulling image: Error response from daemon: manifest for xxx/capesos-from-gentoo/luet:3c43d4317f705b63797d8a6a2a7e1b7ef8e9a448b5bcadc8791e344bfc7bc7f7 not found: manifest unknown: manifest unknown
: exit status 1[0m`

Then, same behavior as above, emerge trouble during emerge @xfce, but it's ok.


So, with only `--target-package-only`, all dep from portage-tree are built and stored in `build/` folder, and all `builder-*` images are rebuilt.

**Comment by mudler** [comment]
@welele08 please file a new issue. 

From the extract I already see that your package is the first one being compiled. In that case, you can't reuse the same images - but you are actually generating a completely new tree.

**Comment by mudler** [comment]
Blocked as needs #158 first
