### ISSUE TITLE
Local docker images aren't used with --pull

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#184]
**Luet version:**
0.10.2

**CPU architecture, OS, and Version:**
AMD64

**Describe the bug**
After building a package locally without push the image, when i try to rerun the build luet doesn't use the local image and rebuild it.

**To Reproduce**
`/usr/bin/luet build --no-spinner --emoji=true --color=false --pull --only-target-package --image-repository quay.io/mocaccinocache/kernel-repo-amd64-cache --tree=/build/packages kernel/mocaccino-lts-full kernel/mocaccino-lts-modules kernel/mocaccino-lts-minimal kernel/mocaccino-lts-sources --destination /build/build --backend docker --concurrency 1 --compression gzip`
(2 times)

**Expected behavior**
Luet using local images before build again the same image.

**Comment by geaaru** [comment]
Without `--pull` the local images are used. But the use case could be related to a user that trying to build his package based on core images of official mocaccino tree and he uses the quay.io image.
He never uses `--push` option.

**Comment by mudler** [comment]
@geaaru can you provide the full logs? what packages images are not being re-used? one of the dependencies, or the target ones?

**Comment by geaaru** [comment]
I will try to prepare the steps for reproduce it in the next days/weeks.
