### ISSUE TITLE
Guarantee unique hashes on values file changes

### ISSUE THREAD

**Issue by mudler** [mudler/luet#207]
By changing the values file, the hashtree remains the same, which means it allows to have unreproducible builds

**Is your feature request related to a problem? Please describe.**
Having reproducible builds for combinations of values files

**Describe the solution you'd like**
Use the values file as a salt for the image hashes and/or alternatively the Dockerfile/`build.yaml`. 
By using the rendered file or `build.yaml` as a salt hash, has the advantage of catching also local changes to the build files.
There is a strong preference to use the rendered `build.yaml` over the `values` file - the values file is generic and **might** apply to a group of packages, and not only to just one. 
Using the rendered `build.yaml` instead (or Dockerfile) as a salt hash gives us the guarantee that we have a unique hash only if the values file it's actually modifying the package build instructions. We need also to mutate the hash function to parse the solver assertions as checksums and not as package fingerprint

**Describe alternatives you've considered**

- checksum the rendered result (Dockerfile) and use it as salt for the image hash
- checksum the rendered build.yaml and use it as salt for the image hash
- checksum of the values file and use it as a salt

**Additional context**

~~Blocked by #203 - It should be tackled first in order to ease out this card~~ done

Update: WIP branch in https://github.com/mudler/luet/tree/build_salthash

**Comment by davidcassany** [comment]
IMHO this is not limited to the values files usage, since they are just a templating tool. To my eyes it would be more natural to use the rendered result as hash salt. I understand this is kind of a design choice not doing that, but I can tell this feature is something I had listed on my notes when I first started using `luet`, in my notes it was called `discover changes to build recipe` though :sweat_smile: I kind a missed it when I first started working with it and before having the build workflow clear in my head.

**Comment by mudler** [comment]
@davidcassany how about using the build.yaml file as hash salt? That's what at the end drives the final rendering (so we make it indipendent from the result, that can be a Dockerfile, or.. )

**Comment by davidcassany** [comment]
> @davidcassany how about using the build.yaml file as hash salt? That's what at the end drives the final rendering (so we make it indipendent from the result, that can be a Dockerfile, or.. )

Yes I think that would make sense if this is applied on the rendered build.yaml. We need to make sure the hash changes if the values used for templating change.

**Comment by geaaru** [comment]
Just a note, i'm not sure that could be related. In the virtual packages atm, we use an empty `build.yaml` file that it could be avoided completely in the near future. The use of build.yaml to generate the hash should to consider this use case.

**Comment by mudler** [comment]
> Just a note, i'm not sure that could be related. In the virtual packages atm, we use an empty `build.yaml` file that it could be avoided completely in the near future. The use of build.yaml to generate the hash should to consider this use case.

If we use it only as a salt it should be fine, it is still unique
