### ISSUE TITLE
Don't always refresh repository metadata

### ISSUE THREAD

**Issue by mudler** [mudler/luet#212]
**Is your feature request related to a problem? Please describe.**
Every time I do `luet search`, repositories get refreshed and gets in the middle of my daily workflow

**Describe the solution you'd like**
Refresh to happen whenever necessary unless explictly the user wants to do it manually. Check if the database is too old (e.g. 1 day ) and force a refresh only in that case.

**Describe alternatives you've considered**

**Additional context**

**Comment by manifestonosuke** [comment]
My preferred option would be to never force an update but display a message on the last update time like : 
```
 INFO   Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )                                                  
 INFO   Repository mocaccino-repository-index last update XX days ago.
```
