### ISSUE TITLE
Install of repository-index fail in luet 0.14.5

### ISSUE THREAD

**Issue by welele08** [mudler/luet#215]
**Luet version:**
0.14.5

**CPU architecture, OS, and Version:**
x86_64, ubuntu
**Describe the bug**
During get_luet script, installation of luet of mocaccino-repository-index fail while accessing tar.gz with 
` 📦  Package  repository/mocaccino-repository-index-20201005 downloaded`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x18dafdd]`
`goroutine 101 [running]:`
`github.com/mudler/luet/pkg/compiler/types/artifact.tarModifierWrapperFunc(0x30c348f, 0x1, 0xc00024b3a0, 0x1e, 0xc0004247e0, 0x216e7e0, 0xc000209440, 0x0, 0x0, 0x0, ...)`
`	/home/runner/work/luet/luet/pkg/compiler/types/artifact/artifact.go:401 +0x8dd
github.com/mudler/luet/pkg/helpers.(*TarModifierWrapper).GetModifier.func1(0xc00024b3a0, 0x1e, 0xc0004247e0, 0x216e7e0, 0xc000209440, 0x8, 0x1e, 0x8001, 0x5700000000000000, 0x0, ...)
	/home/runner/work/luet/luet/pkg/helpers/archive.go:68 +0x7c
github.com/docker/docker/pkg/archive.ReplaceFileTarWrapper.func1.1(0xc00024b3a0, 0x1e, 0xc0004247e0, 0xc00007a020, 0x216e7e0, 0xc000209440, 0x0, 0x0)
	/home/runner/work/luet/luet/vendor/github.com/docker/docker/pkg/archive/archive.go:274 +0x77
github.com/docker/docker/pkg/archive.ReplaceFileTarWrapper.func1(0x218b340, 0xc0005c2270, 0xc0005c2288, 0xc0003091d0)
	/home/runner/work/luet/luet/vendor/github.com/docker/docker/pkg/archive/archive.go:324 +0x338
created by github.com/docker/docker/pkg/archive.ReplaceFileTarWrapper
	/home/runner/work/luet/luet/vendor/github.com/docker/docker/pkg/archive/archive.go:267 +0x15c`

**To Reproduce**
Run `curl https://get.mocaccino.org/luet/get_luet_root.sh | sh` in a clean docker container

**Comment by mudler** [comment]
That's fixed in 0.14.6 👍

**Comment by welele08** [comment]
:)
Waiting 0.14.6 deployment :)

**Comment by mudler** [comment]
All should be good now ! :+1:

**Comment by welele08** [comment]
👍
TY!
