### ISSUE TITLE
Failed downloading package

### ISSUE THREAD

**Issue by pkurash** [mudler/luet#249]
**Luet version:**
<luet version 0.17.8-g3402641241fd6459a4c95f6055b98a728c4e2c67 2021-08-11 01:44:35 UTC
 -->

Hello, I am trying to migrate from Sabayon to Mocaccino OS. After installing luet and Mocaccino OS respositories I give "luet upgrade -y" command, but it stops at the download phase yielding the following log:

Failed downloading package X Error on download artifact: context deadline exceeded (Client.Timeout or context cancellation while reading body)

As I find after some googling, it is related to Go language, but don't understand how to fix it for luet.

The same error happens with a fresh mocaccino os installation on VM when I attempt to install new packages.

**CPU architecture, OS, and Version:**
<!-Linux Sabayon-pc 5.7.0-sabayon #1 SMP Thu Apr 8 19:33:07 UTC 2021 x86_64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz GenuineIntel GNU/Linux
"  -->

**Describe the bug**
<Luet will not install packages -->

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by geaaru** [comment]
You can increase the timeout limit with the env: `HTTP_TIMEOUT`. Setting a  0 value means no limit.
