### ISSUE TITLE
RFC: Review upgrade process to reduce I/O

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#256]
In particular, when there are used layers (but also on a single package) luet works intensively with i/o but often does this also when is not needed. I mean, on upgrade a package often a lot of files are equal to the previous files.

In this case, luet could avoid removing the file that is equal in the next version.

Obviously, this increases the complexity of the luet engine, so just to see what are the pro and cons:

*cons:*
- more complexity on luet code
- more effort on package build but I think that could be less critical
- metadata is more fat (I think to add an md5 for every file that could be used in the installation phase)

*pro:*
- speedup layer installation
- reduce i/o operations that are slow (on old disk (not SSD) layer upgrade it's something very slow).
- to have md5 for every file it's something that could be used later to validate the existing installation (like `equo sec oscheck`)

WDYT?

**Comment by mudler** [comment]
this is drastically changed over almost a year, and there seems to be no interest. I'll close this one in favor of creating new ones, if needed over the current implementation.
