### ISSUE TITLE
Firefox/thunderbird  installation fails.

### ISSUE THREAD

**Issue by manifestonosuke** [mudler/luet#270]
**Luet version:**
luet version 0.20.8-gc58a462e79f64664e0546dec57fb8e00e02b50cf 2021-11-06 10:10:37 UTC

**CPU architecture, OS, and Version:**
Linux Mocaccino 5.10.76-mocaccino #5.10.76-Mocaccino SMP Mon Nov 1 14:48:33 UTC 2021 x86_64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz GenuineIntel GNU/Linux

**Describe the bug**
When I try to install thunderbird (same issue with FF) it fails see attached files.
[](url)

**To Reproduce**
```
luet --debug  install apps/thunderbird 2>&1 | tee -a /tmp/thunderbird.debug
luet --debug  install apps/firefox 2>&1 | tee -a /tmp/firefox.debug

```
**Expected behavior**
Package installed.

**Logs**
[firefox.debug.txt](https://github.com/mudler/luet/files/7527955/firefox.debug.txt)
[thunderbird.debug.txt](https://github.com/mudler/luet/files/7527966/thunderbird.debug.txt)

**Comment by mudler** [comment]
Looks like you have the mocaccino-desktop development repository enabled, not the stable one

**Comment by joostruis** [comment]
Please do not report these issues if you are not on stable repo.

**Comment by manifestonosuke** [comment]
I moved to stable repo with : 
`luet uninstall repository/mocaccino-desktop
wget https://raw.githubusercontent.com/mocaccinoOS/repository-index/master/packages/mocaccino-desktop-stable.yml -O /etc/luet/repos.conf.d/mocaccino-desktop-stable.yml
luet cleanup 
luet install apps/thunderbird
`
