### ISSUE TITLE
Unpack local image 

### ISSUE THREAD

**Issue by Ludea** [mudler/luet#275]
**Is your feature request related to a problem? Please describe.**

I use cos toolkit to build a derivative. 
When using arm builder, instead of unpack the built img, it pull and unpack downloaded img 
 
**Describe the solution you'd like**

I would like to unpack a local image

**Describe alternatives you've considered**

**Additional context**

https://github.com/mudler/luet/blob/bb88fe7e9cbdce2a59edc8068c27bb4603ded5f0/pkg/helpers/docker/docker.go#L130 maybe split this func into 2 func and add an option to `luet util unpack`to specify local image name

**Comment by mudler** [comment]
good point, definetly luet util unpack can take an optional `--local` flag
