### ISSUE TITLE
local flag is unknow

### ISSUE THREAD

**Issue by Ludea** [mudler/luet#278]
**Luet version:**

0.22.4
**CPU architecture, OS, and Version:**

Ubuntu 20.04, amd64 
**Describe the bug**

I try to use luet to unpack local image
**To Reproduce**

Run luet util unpack localimage:tag directory --local 
**Expected behavior**

Unpack local container image 
**Logs**

`unknown flag: --local
  luet util unpack image path [flags]
`
**Additional context**

https://github.com/Ludea/sgnOS/runs/4664554632?check_suite_focus=true#step:9:30

**Comment by mudler** [comment]
@Ludea how are you using it? I see it available:

```
luet util unpack --help                                                                                  
unpack doesn't need the docker daemon to run, and unpacks a docker image in the specified directory:
                                                           
        luet util unpack golang:alpine /alpine                                                                        
                                                                                                                      
Usage:                                                                                                                
  luet util unpack image path [flags]             
                                                                                                                      
Flags:                                        
      --auth-identity-token string   Authentication identity token                 
      --auth-password string         Password to authenticate to registry        
      --auth-registry-token string   Authentication registry token      
      --auth-server-address string   Authentication server address
      --auth-type string             Auth type                                                                        
      --auth-username string         Username to authenticate to registry/notary         
  -h, --help                         help for unpack
      --local                        Unpack local image
      --verify                       Verify signed images to notary before to pull

```

Which seems to work fine here:

```
$> luet util unpack --local alpine test
 INFO   Downloading alpine to /home/mudler/test
 INFO   Size: 5.322MiB
```

**Comment by Ludea** [comment]
I use it with luet container
https://github.com/Ludea/sgnOS/blob/521126ccb81411ae2f083f50a4b5fdc3a8fb58a7/images/arm-img-builder.sh#L306

**Comment by mudler** [comment]
> I use it with luet container https://github.com/Ludea/sgnOS/blob/521126ccb81411ae2f083f50a4b5fdc3a8fb58a7/images/arm-img-builder.sh#L306

I think it's due to the fact the pipelines are running a version of luet without that flag, see: 
```
 INFO   📦  Package  toolchain/luet-0.21.2-1 installed
```

**Comment by Ludea** [comment]
https://api.github.com/repos/mudler/luet/releases/latest point to 0.22.4, which is the latest 🤷

**Comment by Ludea** [comment]
Maybe https://github.com/rancher-sandbox/cOS-toolkit/pull/1031 is relevant ?

**Comment by mudler** [comment]
yep definetly looks like it, `cOS` still doesn't have the `luet` version with the `--local` flag to `unpack`

**Comment by mudler** [comment]
@Ludea Should be available now!

**Comment by Ludea** [comment]
Yes I confirm ! So closing it
