### ISSUE TITLE
Build apparently succeeds, always fails at Delta generation step

### ISSUE THREAD

**Issue by msdobrescu** [mudler/luet#301]
**Luet version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

Every build in the community repo fails with a message like:
  ERROR    Error: Error met while generating delta: Failed saving image: Error response from daemon: reference does not exist

I don't see it build at all, actually. No emerge, no steps.

**To Reproduce**

**Expected behavior**

**Logs**

https://github.com/mocaccinoOS/community-repository/runs/7055165135?check_suite_focus=true#step:9:2100

**Additional context**

I was syncing community repo with the latest changes in the main repos. I've [successfully rebuilt a batch of packages](https://github.com/mocaccinoOS/community-repository/actions/runs/2558037825) over night. Next morning I was trying to continue with the next batch. That [failed](https://github.com/mocaccinoOS/community-repository/runs/7051718825?check_suite_focus=true#step:9:1847) early:

```
  ERROR    Error: while resolving join images: could not generate image hash: Error while generating compilespec for yip: Candidate not found: No versions found for: utils/yip->=0.7.3
```
I have [added a repo](https://github.com/mocaccinoOS/community-repository/commit/4174e4b8886ae2befa037d58a22af661d3dbef39) that made it go further.

And so, it fails with this docker error.

**Comment by mudler** [comment]
After debugging with @msdobrescu  this turned out to be a repository misconfiguration due to the cleanup plugin being too much aggressive. Closing
