### ISSUE TITLE
Provide `marcosnils/bin`  as an alternate installation method

### ISSUE THREAD

**Issue by joe733** [mudler/luet#334]
[`bin`](https://github.com/marcosnils/bin) can grab proper `luet` version from `https://github.com/mudler/luet/releases`.

So in the `README.md` you can have:

```markdown

## Install

- **Using official installer script:**

    ```console
    $ curl https://luet.io/install.sh | sudo sh
    ```

- **Or using [`bin`](https://github.com/marcosnils/bin)**

    ```console
    $ bin i github.com/mudler/luet
    ```

### Test installation:

```console
$ luet --help
$ luet search ...
$ luet install ..
.```
```

---

> Preview

## Install

- **Using official installer script:**

    ```console
    $ curl https://luet.io/install.sh | sudo sh
    ```

- **Or using [`bin`](https://github.com/marcosnils/bin)**

    ```console
    $ bin i github.com/mudler/luet
    ```

### **Test installation:**

```console
$ luet --help
$ luet search ...
$ luet install ..
```

---

Are PRs on this welcome?

**Comment by Itxaka** [comment]
hat bin tihng is pretty handy, sure will help me manage my 100 of binaries downloaded from github! I would say a PR to add would be very helpful!
