### ISSUE TITLE
Luet v0.35.1 show incorrect version as v0.34.0

### ISSUE THREAD

**Issue by nianyush** [mudler/luet#352]
https://github.com/kairos-io/kairos/issues/2370#issuecomment-2008696336

**Comment by jimmykarily** [comment]
Needs to be passed wtih ldflags like the rest: https://github.com/mudler/luet/blob/4c788ccbd18e287c15c9610594daa533b53ffdad/cmd/root.go#L33 

so that it gets it from the latest tag.

**Comment by nianyush** [comment]
fixed by https://github.com/mudler/luet/pull/353
