### ISSUE TITLE
Optimize build cache

### ISSUE THREAD

**Issue by mudler** [mudler/luet#37]
We do perform operations that can be skipped in local iterations (e.g. export of image if no changes are detected, etc)

**Comment by geaaru** [comment]
It's important to add an in-memory history of the built images to avoid this use case in a single running phase.

```bash
$# luet install cat/app1 cat/app2
```
Both `app1` and `app2` have as requirements `layer/l1` and `layer/l2` and also in the single execution, both layer/l1 and layer/l2 currently rebuilt two times.

**Comment by mudler** [comment]
We now have ```build --clean=false``` to skip packages to be built if they are already in the target dir. To handle shared dependency, I've created a separate issue #41
