### ISSUE TITLE
Feature: luet box

### ISSUE THREAD

**Issue by mudler** [mudler/luet#45]
As for now, it's easy to compose a new rootfs formed from different specfiles.
The PM can already assemble the image in a portable fashion.

E.g. 

     luet build ..

     luet install --system-target /foo --system-db /foo/luet.db

The proposal is to combine in a 'wrapper around' way `luet box`:

- `luet box create "foo" --packages <pkg1> --packages <pkg2>`: It creates a
  new box from the given packages. It merely installs on a pre-defined folders
  and reassembles the image
- `luet box delete "foo"`: delete the box
- `luet box install "foo" <pkg1> <pkg2>`: Install packages in the box
- `luet box uninstall "foo" <pkg1> <pkg2>`: Uninstall packages in the box
- `luet box upgrade "foo"`: Upgrades packages in the box
- `luet box run "foo" /my/command`: Execute a command in a box
- `luet box shell "foo"`: Opens up an interactive shell in the box

~Note: 
To achieve this there is only a functional limitation. The implementation must
provide also a way for finalizers to perform commands in the given
environment(box).~

**Comment by geaaru** [comment]
In general, for this, we could do this through `distrobuilder` tool from canonical. I already create a patch in my fork for use luet. As start rootfs we could use luet/base image.

**Comment by geaaru** [comment]
https://github.com/geaaru/distrobuilder/commit/eea221b1b2c17c3b62bc7242e4fdd322ece583dd (WIP)

**Comment by mudler** [comment]
First step into this direction: https://github.com/mudler/luet/commit/49d7b4e2bf6df697666a34bb7bfdca645b0599e7

**Comment by mudler** [comment]
Support for env and hostmounts in `box exec` : https://github.com/mudler/luet/commit/98876c8f20b8252fa906e0cc3ed174e38b8cffa5
Fixups: https://github.com/mudler/luet/commit/4cee27da7fc208903cfd5e5167004c772a40576f 
Support to specify mount target on the box: https://github.com/mudler/luet/commit/9321a310a524a2ca03ff3ca5cfdf07f36e345e24

**Comment by geaaru** [comment]
Between tasks... add support for boxes as profiles.
Under `/etc/luet/boxes/*.yml` where yaml file is in the form:
```yaml
boxes:
- name: "Box1"
  rootfs: /luet/boxes/box1
```
Here could be also single box for file.
In this way, we could execute then:
```shell
$> luet box install -p Box1 <pkg1>
$> LUET_BOX_DEFAULT=Box1 luet box install <pkg1>
```
The main configuration will contains:
```yaml
boxes:
   confdir: /etc/luet/boxes/
   default: "default"
```

**Comment by mudler** [comment]
I'll close this - there is now `extension/container` in luet-repo which is a simple bash plugin wrapping luet to achieve this
