### ISSUE TITLE
Feature: luet database

### ISSUE THREAD

**Issue by mudler** [mudler/luet#47]
We should have a command to:

- Remove packages from system forcefully (delete only the entry from DB if necessary, with ``--force`` flag)
- Add packages in system forcefully (even accepting the metadata yaml as source, with a list of e.g. files that belongs to the package)

**Comment by geaaru** [comment]
What's the spec of metadata.yaml used?

Something like this:
```golang
type PackageFile struct {
     FilePath  string
     Checksum Checksums
}

type PackageArtifactMeta struct {
   *PackageArtifact
   Files []PackageFile
}
```
