### ISSUE TITLE
Add aarch64 builds to releases

### ISSUE THREAD

**Issue by necrose99** [mudler/luet#57]
works thus far in chroot. 

[luet-aarch64-linux.zip](https://github.com/mudler/luet/files/4209086/luet-aarch64-linux.zip)
![Annotation 2020-02-15 171028](https://user-images.githubusercontent.com/2396239/74596528-25172d80-5016-11ea-9a76-d680ab62599c.png)

**Comment by necrose99** [comment]
been cobeeling back my gentoo on rock64pro..

**Comment by mudler** [comment]
That's awesome! thanks for letting us know, I guess makes sense to enable aarch64 builds as well!

**Comment by mudler** [comment]
This seems to be relevant: https://github.com/mitchellh/gox/issues/92

**Comment by necrose99** [comment]
your docker packer arm7hf ebuild for _docker-companion_   its not aarch64 persey but so long as the _kernel has arm32 support &  aarch64 kernel_  it will build from ebuild if forced. 
ie ebuild file package..    however kernel/s on [scaleway](https://www.scaleway.com/en/virtual-instances/arm-instances/) are often 64 only untill custom recompiled on debian hosts 


for giiglles the pull i punted a few extra's ie risckv everyone and thier bro is porting too,... 
https://github.com/mitchellh/gox/issues/140 
however others have other go files patched besides rigging platform.go for more... 
my 3 min hack , but windows builds stupid resin-xbuild... /bin/sh qemu wrapper.  

https://github.com/jeroenjacobs79/tobw/blob/develop/Makefile builds even more targets in MAKEFILE... and arm/aarch64 for bsd. flavors .. 
MottainaiCI builds rather simply only not having a public sabayon swarm etc to join to when idle to build n ship via docker queeing..  for arm64.  on devices.. 

steel a page of https://boinc.berkeley.edu/ 
at present riscv is avlible in golang , but not gox i however can get BSD arm or likewise the BSD dev used a make file with even more targets.  platforms .go in gox a few others got pulls but gox seems to slowisshly  need distros to take the pulls to diffs and patching or owner has perhaps not keept up on those. 
mot bakes in gentoo rpi3/4 form Sakaki- or scaleway gentoo chroot , 
and if being a wiseArse ... 

ebuild fooo rpm , spec rpm alien deb > can be outed too if users are using a deb/rpm based servers/ to host thier dockers common on Packet of late has hosted gentoo org for free @arrch64 
after last cloud build of crossdev @ 85 bucks over budget i moved to Amsterdams scaleway ,,

**Comment by necrose99** [comment]
https://github.com/dgraph-io/badger might be worth a look for storing db data on the fly. 
whith packages and deps if not using rust/sqlite ... 

https://github.com/necrose99/gentoo-binhost  i forked off to have a hostable option without having to rent a www/1-2 TB per mo.. 

this could be likewise used with entropy or rusted-entropy (py-to-rust / and or rust to go) 
repos.. 
ie could guesst for community repo of sab... pull to offer packages back .. 
ie re-spins ie quem with Power user features or more arches. 
but for now the gentoo-binhost..

**Comment by necrose99** [comment]
- [ ] [vendor.log.txt](https://github.com/mudler/luet/files/4810312/vendor.log.txt)
**pentoo scripts ego vendor....**  **useful in making go ebuilds** 
[luet-0.8.0-aarch64-linux.zip](https://github.com/mudler/luet/files/4810322/luet-0.8.0-aarch64-linux.zip)

https://github.com/sakaki-/gentoo-on-rpi-64bit
runs either amr32 or aarch64 on rpi4 , (arrch64 with 32 bit bin support in kernel) 
built latest on rpi4-4gig ram

**Comment by Itxaka** [comment]
There is now arm64 builds on the release page, but Im sure those are not tested. Do they work for you @necrose99 ?

**Comment by necrose99** [comment]
[luet-0.8.0-aarch64-linux.zip](https://github.com/mudler/luet/files/4810322/luet-0.8.0-aarch64-linux.zip)
takes 35-65 mins to build etc. by hand with releases on hand ... 

https://github.com/MottainaiCI ALSO will build via ebuild/s without much troubles  
rpi4 gentoo @ idle subscribe to workflows :blindfold:  do builds in pillaged docker with no knowledge send back results .. 
ie add a sudo service account , api keys for **zero knowledge / zero-trust** 
crowdsourced among users ...... wala   one can wishlist , 

https://pypi.org/project/fchroot/  Funtoo franken chroot aarch64-qumu and walla a Ryzen9 16/32 core / thread ripper would make short work  or https://bitscope.com/product/blade/?p=about  rpi4 blade/cluster  for getting a base MoC.OS arm64 out. 

Grub will build so with uefi image  @mocaccinoos for arm64 could easily update kernels without much hell..  genpi64 has a binhost hopefully with this on tap an RPi4 build of mocaccinoos  could be done.  which would be a slight improvement over the defacto genpi64 legacy non-efi  image. 
https://discord.gg/VyQ5TPaK Genpi64 discord 

@pentoo and automation items would be quite useful / i build these often by hand however having cloud not having to build the base toys/os bits would be a plus.  luet/MottainaiCI automation also nice to haves. 
( ie the lower end drudge work ..  so one can build other underlying with MoC.OS existing automation ) 
by hand the updating gentoo to run pentoo , or alike and or updates .....  takes a prodding along for a week/7-9 days let alone update drifting (if i didnt have those pesky os / office base python ruby....... to rebuild..... ) 
sure having kali linux would be far easier , but i'd prefer the wheat from the chaff in terms of tools  

https://wiki.gentoo.org/wiki/User:Maffblaster/Projects/GenPi64 
https://github.com/GenPi64  https://github.com/GenPi64/gentoo-on-rpi-64bit/archive/refs/tags/v1.6.0.tar.gz 
https://github.com/GenPi64/Build.Dist 


@mudler luet-qchroot  fchroot alike logic might be a slight improvement on roadmap
