### ISSUE TITLE
add --enable-log and --disable-log flag to enable/disable logging. (disabled by default)

### ISSUE THREAD

**Issue by jcfrosty** [mudler/luet#98]
Luet needs default logging directory (/var/log/luet/luet.log) for standardization and the ability to enable/disable logging from the command.

e.g. ``--enable-log`` as a persistent parameter to enable logging on the file which is set by default  in the config file

**Comment by geaaru** [comment]
Done with commit fe5ab9246f5eea8f07baee484e1d0e99d83b97cd and add support for these additional options 13df161fc6a61a4b0ba5d8b2f941fc2c3c0a3b2e

The issue can be closed just when PR https://github.com/mudler/luet/pull/109 is merged
